import type { Metadata } from "next";
import { Viaoda_Libre } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layouts/Footer";

const inter = Viaoda_Libre({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
